version: '3.8'

services:
  pizza-app:
    container_name: ${DOCKER_NODE_NAME}
    hostname: ${DOCKER_NODE_NAME}
    image: ${DOCKER_IMAGE_NAME}
    tty: true
    build:
      context: .
      target: app
    environment:
      - NODE_ENV=${NODE_ENV}
      - FRONT_HOST=${FRONT_HOST}
    volumes:
      - ./:/home/app
    ports:
      - ${PORT}:${PORT}
    networks:
      - local

networks:
  local:
    name: "${DOCKER_NETWORK_NAME}"
