name: Deploy CD

run-name: DEPLOY 🚀

on: [push]

jobs:
  deploy-development:
    runs-on: ubuntu-latest

    if: github.event.pull_request.base.ref == 'development'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js with yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Create env file
        run: touch .env

      - name: Copy env file
        run: cp .env.local .env

      - name: Build
        shell: sh
        run: make build-container

      - name: Kill container
        shell: sh
        run: make compose-down-v
