name: Lint CI

run-name: Lint 🚀

on: [pull_request]

env:
  DC: docker compose -f docker-compose.local.yml

jobs:
  lint-development:
    runs-on: ubuntu-latest

#    if:  github.ref_name == 'development'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js with yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: shit
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create env file
        run: touch .env

      - name: Copy env file
        run: cp .env.local .env

      - name: Build
        shell: sh
        run: make build-container

      - name: Run lint in container
        shell: sh
        run: make docker-run-install-lint

      - name: Kill container
        shell: sh
        run: make compose-down-v
